# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelDel_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form3):
        Form3.setObjectName("Form3")
        Form3.resize(553, 229)
        self.formLayout = QtWidgets.QFormLayout(Form3)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(Form3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.labelProiz = QtWidgets.QLabel(Form3)
        self.labelProiz.setText("")
        self.labelProiz.setObjectName("labelProiz")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelProiz)
        self.label = QtWidgets.QLabel(Form3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.labelModel = QtWidgets.QLabel(Form3)
        self.labelModel.setText("")
        self.labelModel.setObjectName("labelModel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelModel)
        self.label_6 = QtWidgets.QLabel(Form3)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(Form3)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(Form3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_2 = QtWidgets.QLabel(Form3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.labelYear = QtWidgets.QLabel(Form3)
        self.labelYear.setText("")
        self.labelYear.setObjectName("labelYear")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelYear)
        self.label_3 = QtWidgets.QLabel(Form3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.labelCena = QtWidgets.QLabel(Form3)
        self.labelCena.setText("")
        self.labelCena.setObjectName("labelCena")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelCena)
        self.label_9 = QtWidgets.QLabel(Form3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.labelDate = QtWidgets.QLabel(Form3)
        self.labelDate.setText("")
        self.labelDate.setObjectName("labelDate")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.labelDate)
        self.pushButtonDel = QtWidgets.QPushButton(Form3)
        self.pushButtonDel.setObjectName("pushButtonDel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButtonDel)
        self.label_5 = QtWidgets.QLabel(Form3)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.labelType = QtWidgets.QLabel(Form3)
        self.labelType.setText("")
        self.labelType.setObjectName("labelType")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelType)
        self.labelRegion = QtWidgets.QLabel(Form3)
        self.labelRegion.setText("")
        self.labelRegion.setObjectName("labelRegion")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelRegion)
        self.labelDiller = QtWidgets.QLabel(Form3)
        self.labelDiller.setText("")
        self.labelDiller.setObjectName("labelDiller")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelDiller)

        self.retranslateUi(Form3)
        QtCore.QMetaObject.connectSlotsByName(Form3)

    def retranslateUi(self, Form3):
        _translate = QtCore.QCoreApplication.translate
        Form3.setWindowTitle(_translate("Form3", "Удалить модель"))
        self.label_4.setText(_translate("Form3", "Производитель"))
        self.label.setText(_translate("Form3", "Модель"))
        self.label_6.setText(_translate("Form3", "Тип"))
        self.label_7.setText(_translate("Form3", "Регион"))
        self.label_8.setText(_translate("Form3", "Диллер"))
        self.label_2.setText(_translate("Form3", "Год выпуска"))
        self.label_3.setText(_translate("Form3", "Цена"))
        self.label_9.setText(_translate("Form3", "Дата покупки"))
        self.pushButtonDel.setText(_translate("Form3", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form3 = QtWidgets.QWidget()
    ui = Ui_Form3()
    ui.setupUi(Form3)
    Form3.show()
    sys.exit(app.exec_())
