# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchcars_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 626)
        MainWindow.setStyleSheet("#MainWindow{background-color:green}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("tabWidget{background-color:rgb(193, 255, 200)}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 771, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 771, 35))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonAdd = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonAdd.setStyleSheet("QPushButton {\n"
"background-color: yellow;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;;\n"
"}")
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_4.addWidget(self.pushButtonAdd)
        self.pushButtonChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonChange.setStyleSheet("QPushButton {\n"
"background-color: yellow;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 5px;;\n"
"}")
        self.pushButtonChange.setObjectName("pushButtonChange")
        self.horizontalLayout_4.addWidget(self.pushButtonChange)
        self.pushButtonDel = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonDel.setStyleSheet("QPushButton {\n"
"background-color: yellow;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 5px;;\n"
"}")
        self.pushButtonDel.setObjectName("pushButtonDel")
        self.horizontalLayout_4.addWidget(self.pushButtonDel)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonUpdate.setStyleSheet("QPushButton {\n"
"background-color: yellow;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 5px;;\n"
"}")
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.horizontalLayout_4.addWidget(self.pushButtonUpdate)
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setGeometry(QtCore.QRect(795, 10, 291, 521))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_6 = QtWidgets.QLabel(self.splitter)
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.splitter)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_7 = QtWidgets.QLabel(self.splitter)
        self.label_7.setObjectName("label_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 480, 771, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.comboBoxProizvod = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBoxProizvod.setObjectName("comboBoxProizvod")
        self.gridLayout.addWidget(self.comboBoxProizvod, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.comboBoxType = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBoxType.setObjectName("comboBoxType")
        self.gridLayout.addWidget(self.comboBoxType, 1, 2, 1, 1)
        self.comboBoxRegion = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBoxRegion.setObjectName("comboBoxRegion")
        self.gridLayout.addWidget(self.comboBoxRegion, 1, 3, 1, 1)
        self.comboBoxModel = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBoxModel.setObjectName("comboBoxModel")
        self.gridLayout.addWidget(self.comboBoxModel, 1, 1, 1, 1)
        self.pushButtonFilter = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonFilter.setStyleSheet("QPushButton {\n"
"    background-color: rgb(118, 49, 255);\n"
"    border-radus: 10px;\n"
"}")
        self.pushButtonFilter.setObjectName("pushButtonFilter")
        self.gridLayout.addWidget(self.pushButtonFilter, 1, 4, 1, 1)
        self.pushButtonClsFilter = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonClsFilter.setStyleSheet("QPushButton {\n"
"    background-color: rgb(118, 49, 255);\n"
"    border-radus: 10px;\n"
"}")
        self.pushButtonClsFilter.setObjectName("pushButtonClsFilter")
        self.gridLayout.addWidget(self.pushButtonClsFilter, 1, 5, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(370, 80, 381, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(280, 500, 541, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.labelGif = QtWidgets.QLabel(self.tab_3)
        self.labelGif.setGeometry(QtCore.QRect(250, 120, 521, 331))
        self.labelGif.setText("")
        self.labelGif.setObjectName("labelGif")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Покупка автомобилей"))
        self.label.setText(_translate("MainWindow", "                                                                         Менеджер покупки автомобилей"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Производитель"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Тип"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Модель"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Регион"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Центр дилера"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Дата покупки"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Добавить модель"))
        self.pushButtonChange.setText(_translate("MainWindow", "Редактировать модель"))
        self.pushButtonDel.setText(_translate("MainWindow", "Удалить модель"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Обновить таблицу"))
        self.label_6.setText(_translate("MainWindow", "                      ИЗОБРАЖЕНИЕ АВТОМОБИЛЯ"))
        self.label_7.setText(_translate("MainWindow", "                                 ТХ АВТОМОБИЛЯ"))
        self.label_4.setText(_translate("MainWindow", "Модель"))
        self.label_3.setText(_translate("MainWindow", "Тип"))
        self.label_5.setText(_translate("MainWindow", "Регион"))
        self.label_8.setText(_translate("MainWindow", "Производитель"))
        self.pushButtonFilter.setText(_translate("MainWindow", "Фильтр"))
        self.pushButtonClsFilter.setText(_translate("MainWindow", "Сбросить фильтр"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Поиск"))
        self.label_10.setText(_translate("MainWindow", "Менеджер покупки автомобилей"))
        self.label_11.setText(_translate("MainWindow", ""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "О программе"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
